// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1WIt3U5egF0FIdHEgj3iQjHSGXHDdSUQ',
    appId: '1:175076421876:web:5e5ce89e02e6760d31aea1',
    messagingSenderId: '175076421876',
    projectId: 'mobilep9-79fb4',
    authDomain: 'mobilep9-79fb4.firebaseapp.com',
    storageBucket: 'mobilep9-79fb4.firebasestorage.app',
    measurementId: 'G-R40YHN9Q9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAomvgTXxCE563PRxrJoNBarwUzZArc4NI',
    appId: '1:175076421876:android:f90fa5480a95757a31aea1',
    messagingSenderId: '175076421876',
    projectId: 'mobilep9-79fb4',
    storageBucket: 'mobilep9-79fb4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1WIt3U5egF0FIdHEgj3iQjHSGXHDdSUQ',
    appId: '1:175076421876:web:7392492af249fc6b31aea1',
    messagingSenderId: '175076421876',
    projectId: 'mobilep9-79fb4',
    authDomain: 'mobilep9-79fb4.firebaseapp.com',
    storageBucket: 'mobilep9-79fb4.firebasestorage.app',
    measurementId: 'G-YWD3C0KDQT',
  );
}
